const PricingSection = () => {
  return (
    <section id="pricing" className="py-24 px-6">
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-6">
          <span className="inline-block bg-primary/10 text-primary font-montserrat text-xs font-bold tracking-[0.2em] uppercase px-4 py-2 rounded-full mb-4">
            Pricing
          </span>
          <h2 className="font-montserrat font-bold text-4xl text-foreground mb-4">
            Choose Your Plan
          </h2>
        </div>
        <div className="grid md:grid-cols-3 gap-6 mb-16 text-center">
          <div className="bg-white/5 border border-white/10 rounded-xl p-6">
            <p className="font-montserrat text-sm font-bold text-primary uppercase tracking-wider mb-2">Per Robot Pricing</p>
            <p className="font-opensans text-sm text-muted leading-relaxed">Each strategy is individually licensed per MT5 account. You choose the asset and plan that best fits your profile.</p>
          </div>
          <div className="bg-white/5 border border-white/10 rounded-xl p-6">
            <p className="font-montserrat text-sm font-bold text-primary uppercase tracking-wider mb-2">Ongoing Support</p>
            <p className="font-opensans text-sm text-muted leading-relaxed">All plans include WhatsApp support, periodic updates, and monitoring throughout the entire contract period.</p>
          </div>
          <div className="bg-white/5 border border-white/10 rounded-xl p-6">
            <p className="font-montserrat text-sm font-bold text-primary uppercase tracking-wider mb-2">Brazil Partnership</p>
            <p className="font-opensans text-sm text-muted leading-relaxed">Exclusive plan for the Brazilian market. No monthly fee — you only pay a commission on the profit generated by the bot.</p>
          </div>
        </div>
        <div className="flex flex-wrap justify-center gap-8 items-stretch">
          <div className="flex-1 min-w-[240px] max-w-[280px] rounded-2xl overflow-hidden hover:-translate-y-2 transition-transform duration-200 cursor-pointer flex flex-col">
            <div className="bg-[#1a5fa8] px-5 py-4 text-center">
              <p className="font-montserrat font-bold text-white text-base">Semi-Annual</p>
            </div>
            <div className="bg-[#2d7dd2] px-5 py-6 flex flex-col gap-4" style={{boxShadow:'0 6px 0 #0d3d6e',borderRadius:'0 0 16px 16px'}}>
              <div className="text-center">
                <p className="font-montserrat font-bold text-white text-3xl">$149</p>
                <p className="font-opensans text-white/70 text-xs mt-1">for 6 months</p>
              </div>
              <div className="border-t border-white/20 pt-4 flex flex-col gap-2">
                {['1 MT5 license','Updates included','Support included','WhatsApp support'].map(item => (
                  <div key={item} className="flex items-center gap-2">
                    <div className="w-1.5 h-1.5 rounded-full bg-white/70 flex-shrink-0" />
                    <span className="font-opensans text-white text-xs">{item}</span>
                  </div>
                ))}
              </div>
              <a href="https://wa.me/5551997337388" target="_blank" rel="noopener noreferrer" className="mt-2 block text-center bg-white/20 hover:bg-white/30 border border-white/40 text-white font-montserrat font-bold text-sm py-2.5 rounded-xl transition-all">
                Chat on WhatsApp ↗
              </a>
            </div>
          </div>
          <div className="flex-1 min-w-[200px] max-w-[240px] rounded-2xl overflow-hidden hover:-translate-y-2 transition-transform duration-200 cursor-pointer">
            <div className="bg-[#3a7d1e] px-5 py-4 text-center">
              <p className="font-montserrat font-bold text-white text-base">Annual</p>
            </div>
            <div className="bg-[#5aaa2a] px-5 py-6 flex flex-col gap-4" style={{boxShadow:'0 6px 0 #1f5010',borderRadius:'0 0 16px 16px'}}>
              <div className="text-center">
                <p className="font-montserrat font-bold text-white text-3xl">$249</p>
                <p className="font-opensans text-white/70 text-xs mt-1">per year · best value</p>
              </div>
              <div className="border-t border-white/20 pt-4 flex flex-col gap-2">
                {['1 MT5 license','Updates included','Support included','Priority support'].map(item => (
                  <div key={item} className="flex items-center gap-2">
                    <div className="w-1.5 h-1.5 rounded-full bg-white/70 flex-shrink-0" />
                    <span className="font-opensans text-white text-xs">{item}</span>
                  </div>
                ))}
              </div>
              <a href="https://wa.me/5551997337388" target="_blank" rel="noopener noreferrer" className="mt-2 block text-center bg-white/20 hover:bg-white/30 border border-white/40 text-white font-montserrat font-bold text-sm py-2.5 rounded-xl transition-all">
                Chat on WhatsApp ↗
              </a>
            </div>
          </div>
          <div className="flex-1 min-w-[200px] max-w-[240px] rounded-2xl overflow-hidden hover:-translate-y-2 transition-transform duration-200 cursor-pointer">
            <div className="bg-[#7c3aed] px-5 py-4 text-center">
              <p className="font-montserrat font-bold text-white text-base">Brazil — Commission</p>
            </div>
            <div className="bg-[#9f5ff0] px-5 py-6 flex flex-col gap-4" style={{boxShadow:'0 6px 0 #4c1d95',borderRadius:'0 0 16px 16px'}}>
              <div className="text-center">
                <p className="font-montserrat font-bold text-white text-3xl">0%</p>
                <p className="font-opensans text-white/70 text-xs mt-1">monthly fee · pay only if profitable</p>
              </div>
              <div className="border-t border-white/20 pt-4 flex flex-col gap-2">
                {['Up to 0.25 BTC → 30%','Up to 0.50 BTC → 25%','Above 0.50 BTC → 20%'].map(item => (
                  <div key={item} className="flex items-center gap-2">
                    <div className="w-1.5 h-1.5 rounded-full bg-white/70 flex-shrink-0" />
                    <span className="font-opensans text-white text-xs">{item}</span>
                  </div>
                ))}
              </div>
              <a href="https://wa.me/5551997337388" target="_blank" rel="noopener noreferrer" className="mt-2 block text-center bg-white/20 hover:bg-white/30 border border-white/40 text-white font-montserrat font-bold text-sm py-2.5 rounded-xl transition-all">
                Chat on WhatsApp ↗
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default PricingSection;
